language: node_js
node_js:
- 7.5
cache:
- node_modules
- bower_components
before_install:
- npm install -g grunt-cli snazzy
before_script:
- node_modules/.bin/semistandard --verbose | snazzy
- ./node_modules/.bin/eslint assets/js/*.module.js
- ./node_modules/.bin/eslint assets/js/components/*.js
- ./node_modules/.bin/eslint assets/js/constants/*.js
- # ./node_modules/.bin/eslint assets/js/controllers/*.js
- ./node_modules/.bin/eslint assets/js/controllers/e*.js
- # ./node_modules/.bin/eslint assets/js/core/*.js
- # ./node_modules/.bin/eslint assets/js/directives/*.js
- ./node_modules/.bin/eslint assets/js/filters/*.js
- ./node_modules/.bin/eslint assets/js/services/*.js
- ./node_modules/.bin/eslint assets/js/sharedDirectives/*.js
- ./node_modules/.bin/eslint assets/js/sharedServices/*.js
- # ./node_modules/.bin/eslint assets/js/**/*
script:
- make build
- make test
- grunt coveralls
before_deploy:
  - make pgp
  - export VERSION=$TRAVIS_TAG
  - make dist
  - export RELEASE_LANDING_JS=$(ls dist/js/landing*.min.js)
  - export RELEASE_MY_WALLET_JS=$(ls dist/js/my-wallet*.min.js)
  - export RELEASE_WALLET_JS=$(ls dist/js/wallet*.min.js)
  - npm shrinkwrap --dev
  - zip -r bower_resolution.zip bower_components/*/.bower.json
deploy:
  provider: releases
  api_key:
    secure: E+nnNRUHhKUHpbxE6itpphwI0JyvKkrl/Npr6dXk6RrtudRLolPYxJWrpit7msVOGsdPP8/dQztJq2YJQvVDrjiu19DjiXr4lsLyK8JshenOObbCEawLBC3ZVHMi2wyekg2JIrXdWDdi3heY0bwjmV0udAvAWbu/533NCKLjOSa3M+jKoVenmh9MCz2D7Z21u8BQ4714CrhM16DrSdP58RCEBsQQmK34BUCNfpUl75t7qLkERhCKtkjNSmX1ruT6nkA5UE6oPdUlFehUuo7lAjhe20E4gjEWOiyu9qeUG7qZM8oW4+dOICqGoJ7GhcGZSkL0zarFexKODcjtcG5o1H1hwwcC4zLytB9aHn8IfkUfkI6lH+GER1HNc2nlDwcpnodL3fwuL+/TZcun0ZBrB2KRgDtsvA9CswmrpSnnGIccT79LhhNimhX5nfgdmzQSwOVtx7QmCQDUGrfktlqouWWxcC5OaHYgiZgh+qcK1Js7+SSCimWbKM0jvKBLDGOWELDSbsdZNugCIoLrGvTw4Q/4HZ90CsJV603Z/FdlrC2iHDxAvOcCK6Oa7Ut7aBDPBCUJKEE1mx/g6+KRm7MycZMlxjpnL3bn7a8TmvxVvQ42D5TFJcJq4hz4QNk6CWGvAnS/Lbcuh1HEBg/ND+X8JFYLL0e0zPJhPol1+BQEr38=
  file:
  - "${RELEASE_LANDING_JS}"
  - "${RELEASE_MY_WALLET_JS}"
  - "${RELEASE_WALLET_JS}"
  - npm-shrinkwrap.json
  - bower_resolution.zip
  on:
    repo: blockchain/My-Wallet-V3-Frontend
    tags: true
